### ISSUE TITLE
The google drive link for the dataset is not valid

### ISSUE THREAD

**Issue by ShivamV94** [stangelid/oposum#9]

**Comment by 2302Jerry** [comment]
I also encounterd this issue.

**Comment by stangelid** [comment]
The google link has been updated a while ago and is working now.

**Comment by 2302Jerry** [comment]
Hi，Stangelid, this link still cannot open: https://drive.google.com/u/0/uc?id=1cv8rKWoVr0Pyj6ZYQAiz8DXpMhfG_48b&export=download
Could you please copy the updated link?
